apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-mirror
  namespace: kernelci-pipeline
spec:
  claimRef:
    name: git-mirror
    namespace: kernelci-pipeline
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
   - ReadWriteOnce
...
